apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgoat-ingress
spec:
  ingressClassName: public
  defaultBackend:
    service:
      name: webgoat-service
      port:
        number: 8080