apiVersion: v1
kind: Ingress
metadata:
  name: webgoat-ingress
spec:
  defaultBackend:
    service:
      name: webgoat-service
      port:
        number: 80

kind: Service
metadata:
  name: webgoat-service
spec:
  selector:
    app.kubernetes.io/name: webgoat-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
kind: Deployment
metadata:
  name: webgoat-deployment
  labels:
    app: webgoat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: registry.git.step.polymtl.ca/log8100/equipe11/tp3:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      #   volumeMounts:
      #     - name: webgoat-storage
      #       mountPath: /home/webgoat
      # volumes:
      #   - name: webgoat-storage
      #     persistentVolumeClaim:
      #       claimName: webgoat-pvclaim
      imagePullSecrets:
      - name: regcred
